################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
A_os/drivers/USB/STM32F7/STM32_USB_Device_Library/Class/CDC \
A_os/drivers/USB/STM32F7/STM32_USB_Device_Library/Core \
A_os/drivers/USB/STM32F7/STM32_USB_Host_Library/Class/AUDIO \
A_os/drivers/USB/STM32F7/STM32_USB_Host_Library/Class/CDC \
A_os/drivers/USB/STM32F7/STM32_USB_Host_Library/Class/HID \
A_os/drivers/USB/STM32F7/STM32_USB_Host_Library/Class/MSC \
A_os/drivers/USB/STM32F7/STM32_USB_Host_Library/Class/MTP \
A_os/drivers/USB/STM32F7/STM32_USB_Host_Library/Core \
A_os/drivers/USB/STM32F7/USB_DEVICE/App \
A_os/drivers/USB/STM32F7/USB_DEVICE/Target \
A_os/drivers/USB/STM32F7/USB_HOST/App \
A_os/drivers/USB/STM32F7/USB_HOST/Target \
A_os/drivers/USB/STM32G491/App \
A_os/drivers/USB/STM32G491/Class/CDC \
A_os/drivers/USB/STM32G491/Core \
A_os/drivers/USB/STM32G491/Target \
A_os/drivers/USB/STM32H743/App \
A_os/drivers/USB/STM32H743/Class/CDC \
A_os/drivers/USB/STM32H743/Class/MIDI \
A_os/drivers/USB/STM32H743/Core \
A_os/drivers/USB/STM32H743/Target \
A_os/drivers/USB/STM32U575/App \
A_os/drivers/USB/STM32U575/Class/CDC \
A_os/drivers/USB/STM32U575/Core \
A_os/drivers/USB/STM32U575/Target \
A_os/drivers/codec \
A_os/drivers/external_flash \
A_os/drivers/gpio_utls \
A_os/drivers/internal_adc \
A_os/drivers/internal_dac \
A_os/drivers/internal_rtc \
A_os/drivers/lcd_ili9341 \
A_os/drivers/lcd_st7735 \
A_os/drivers/rmii \
A_os/drivers/sensors/ccs811 \
A_os/drivers/sensors/dht22 \
A_os/drivers/sensors/lis2dw12 \
A_os/drivers/sensors/lps22df \
A_os/drivers/sensors/sht40 \
A_os/drivers/sensors/stts22h \
A_os/drivers/wireless/SX126xRadio \
A_os/drivers/wireless/nrf24l01 \
A_os/kernel \
A_os/kernel/HwDevices \
A_os/kernel/M7_startup/STM32H743 \
A_os/kernel/flash_updater/STM32F446 \
A_os/kernel/flash_updater/STM32G491 \
A_os/kernel/flash_updater/STM32H743_753 \
A_os/modules/WiFi \
A_os/modules/audio \
A_os/modules/dcc \
A_os/modules/dmx512 \
A_os/modules/lwip2.2/App \
A_os/modules/lwip2.2/LwIp/src/api \
A_os/modules/lwip2.2/LwIp/src/apps/altcp_tls \
A_os/modules/lwip2.2/LwIp/src/apps/http \
A_os/modules/lwip2.2/LwIp/src/apps/lwiperf \
A_os/modules/lwip2.2/LwIp/src/apps/mdns \
A_os/modules/lwip2.2/LwIp/src/apps/mqtt \
A_os/modules/lwip2.2/LwIp/src/apps/netbiosns \
A_os/modules/lwip2.2/LwIp/src/apps/smtp \
A_os/modules/lwip2.2/LwIp/src/apps/snmp \
A_os/modules/lwip2.2/LwIp/src/apps/sntp \
A_os/modules/lwip2.2/LwIp/src/apps/tftp \
A_os/modules/lwip2.2/LwIp/src/core \
A_os/modules/lwip2.2/LwIp/src/core/ipv4 \
A_os/modules/lwip2.2/LwIp/src/core/ipv6 \
A_os/modules/lwip2.2/LwIp/src/netif \
A_os/modules/lwip2.2/LwIp/src/netif/ppp \
A_os/modules/lwip2.2/LwIp/src/netif/ppp/polarssl \
A_os/modules/lwip2.2/Target \
A_os/modules/modbus \
A_os/modules/mqtt_client \
A_os/modules/serial_transfers \
A_os/modules/usb_transfer \
A_os_AudioProcesses/STM32H743/AudioProcesses \
Core/Src \
Drivers/STM32H7xx_HAL_Driver/Src \
FATFS/App \
FATFS/Target \
Middlewares/Third_Party/FatFs/src \
Middlewares/Third_Party/FatFs/src/option \

